apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-service
  namespace: crm-saas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crm-service
  template:
    metadata:
      labels:
        app: crm-service
    spec:
      containers:
        - name: crm-service
          image: localhost:5000/crm-crm-service:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: postgres-secret
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_URL_CRM
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
