apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: crm-saas
type: Opaque
stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: change_me_db_password
  DB_URL_AUTH: postgres://admin:change_me_db_password@postgresql:5432/auth_db
  DB_URL_USER: postgres://admin:change_me_db_password@postgresql:5432/user_db
  DB_URL_CRM: postgres://admin:change_me_db_password@postgresql:5432/crm_db
  DB_URL_NOTIF: postgres://admin:change_me_db_password@postgresql:5432/notification_db
