version: '3.8'

services:
  postgresql:
    ports: []
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  redis:
    ports: []
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  rabbitmq:
    ports: []
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  auth-service:
    ports: []
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  user-service:
    ports: []
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  crm-service:
    ports: []
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  notification-service:
    ports: []
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  frontend:
    ports: []
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  nginx:
    ports:
      - "80:8080"
      - "443:8443"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  prometheus:
    ports: []
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  grafana:
    ports: []
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
