apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: crm-saas
data:
  DB_HOST: postgresql
  REDIS_URL: redis://redis:6379/0
  RMQ_URL: amqp://rmquser:rmqpass@rabbitmq:5672/
  AUTH_SERVICE_URL: http://auth-service:8000
  USER_SERVICE_URL: http://user-service:8000
  CRM_SERVICE_URL: http://crm-service:8000
  NOTIF_SERVICE_URL: http://notification-service:8000
